### PR TITLE
Fixed compatibility issues with Gradle 7.x & dependency updates.

### LINKED ISSUE #1: Not compatible with Gradle 7.x
I have a project that I would like to update to use the latest Gradle version 7.1.1. In this project we use your plugin to provide a list of our dependencies to an internal versions endpoint for monitoring the dependencies and alert in case we use dependencies that have any vulnerabilities we should take care of.

The problem is, this plugin does not work with Gradle 7.1.1 and I get the following error message while building:

```
* What went wrong:
A problem was found with the configuration of task ':generateDependencyInfo' (type 'DepInfoTask').
  - In plugin 'com.github.nicholashauschild.dependency-info' type 'com.github.nicholashauschild.depinfo.DepInfoTask' property 'processResourcesTask$gradle_dependency_info_plugin_main' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.1.1/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

It would be great if you could fix this issue!

### PR DESCRIPTION
**Pull request by cluehr**
With this PR the following changes have been made:

* Bumped Gradle version to 4.10.3 (Using a more recent version of Gradle caused compilation issues due to the used dependencies. This requires more work, I did not want to invest at this moment.)
* Bumped dependency versions to the latest ones that are compatible with Gradle 4.x
* Fixed a typo in a method name `getDestinitionDir` -> `getDestinationDir`
* Added the missing annotation to the property `processResourcesTask$gradle_dependency_info_plugin`to make it compatible with Gradle 7.x (Fixes https://github.com/nicholashauschild/gradle-dependency-info-plugin/issues/1)
* Fixed a warning by adding the `STABLE_PUBLISHING` feature preview flag, which is already the default from Gradle 5.0 onwards.

### CODE REVIEW

**Comment by nicholashauschild** [comment]
I like this, but I am unsure of the state of the build and artifact deployment. Since this currently lacks any meaningful branching strategy, I will merge this in tomorrow and try to dig into any issues that arise. If it works, you can test out the SNAPSHOT jar that is produced, and we can figure out if the final release process works after that.

**Comment by cluehr** [comment]
@nicholashauschild, built it locally and published it to my local repo and used it from there. It was working as expected for my usecase and creating the `dependency-info.properties` file.

**Comment by cluehr** [comment]
Hey @nicholashauschild ! Any news on this?

**Comment by nicholashauschild** [comment]
@cluehr Sorry about that, I said I would and then I didn't. 

Well, today I did, and the build failed with an incompatibility with the publishing plugins, and given the state of the build and publish, it might take a bit of time for me to figure out.  Seems as though I might need to get new credentials for JFrog, which might involve having to call them to unlock my account.

Anyways, you might be best off using the locally built jar for now.

**Comment by cluehr** [comment]
@nicholashauschild, thanks for the update and merging the PR. Unfortunately you were right with what you said about the publishing. If there is anything, I can support you with, please let me know.

**Pull request merged**
